export default Object.freeze({
  FETCH_CITY:         'FETCH_CITY',
  FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
  FETCH_CITY_FAIL:    'FETCH_CITY_FAIL',

  SEARCH_CITY:         'SEARCH_CITY',
  SEARCH_CITY_SUCCESS: 'SEARCH_CITY_SUCCESS',
  SEARCH_CITY_FAIL:    'SEARCH_CITY_FAIL',

  FETCH_CITY_START: 'FETCH_CITY_START',
  FETCH_CITY_STOP:  'FETCH_CITY_STOP',

  DELETE_CITY: 'DELETE_CITY',
});
